### ISSUE TITLE
Relative movement commands

### ISSUE THREAD

**Issue by kwshi** [Spaxe/svg-pathd#1]
In addition to the existing absolute position commands specified in uppercase (M, H, V, L, etc.), the SVG spec also permits relative movement commands in lowercase variants (m, h, v, l, etc.) that allow coordinates to be specified _relative to the last position_.

It would be nice to implement those as well, for completeness sake (after all, this module describes itself as a "complete" SVG path constructor).  Plus, it is conceivably convenient in many cases.  

Since Elm requires type names to start with uppercase, I suggest the type names `Md`, `Hd`, `Vd`, `Ld`, etc. (`d` for delta, as in `dx` and `dy`).

**Comment by Spaxe** [comment]
That's a cool idea @kwshi! I hadn't realised the relative path. Thank you for enlightening me on that.

Will tinker with this and see how we go.

**Comment by Spaxe** [comment]
@kwshi Could you take a look at https://github.com/Spaxe/svg-pathd/pull/2 and let me know if the API design is sensible?

**Comment by kwshi** [comment]
Sorry I forgot to get to it!  Was a bit busy the past few days, but it looks good to me!  The lowercase function aliases is a nice touch that hadn't occurred to me.

**Comment by Spaxe** [comment]
No worries - I'm still trying to figure out when to ask for review and when not to :) This is an easy enough API addition, hope it works well.
